server:
    port: 8001
api:
    path: api
    version: v0.0.1
    endpoint:
        snp: ${api.path}/${api.version}/snp
spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    application:
        name: accessible-biotechnology
    sleuth:
        sampler:
            probability: 1
spark:
    home: /usr/local/Cellar/apache-spark/2.4.1/libexec/
    master: local
    app:
        name: ${spring.application.name}
service:
    name: accessible-biotechnology
    description: Accessible Biotechnology Project
swagger:
    contact:
        email: '"info@canm.dev"'
        name: '"Can MOGOL"'
        url: '"www.canm.dev"'
    description: ${service.description}
    license:
        name: '"MIT License"'
        url: '"www.canm.dev/license"'
    termsUrl: '"www.canm.dev/terms"'
    title: ${service.name}
    version: ${api.version}
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
management:
    endpoints:
        web:
            exposure:
                include: "*"

